env:
   global:
     - CONAN_REFERENCE: "ghostmodule-mongodb/1.0"
     - CONAN_CHANNEL: "stable"
     - CONAN_UPLOAD: "https://api.bintray.com/conan/mathieunassar/ghostrobotics"

linux: &linux
   os: linux
   dist: xenial
   language: python
   python: 3.7
   services:
     - docker
osx: &osx
   os: osx
   python: 3.7
   language: generic
matrix:
   include:
      - <<: *linux
        env: CONAN_GCC_VERSIONS=6 CONAN_DOCKER_IMAGE=conanio/gcc6
      - <<: *linux
        env: CONAN_GCC_VERSIONS=7 CONAN_DOCKER_IMAGE=conanio/gcc7
      - <<: *linux
        env: CONAN_GCC_VERSIONS=8 CONAN_DOCKER_IMAGE=conanio/gcc8
      - <<: *osx
        osx_image: xcode9.4
        env: CONAN_APPLE_CLANG_VERSIONS=9.1
      - <<: *osx
        osx_image: xcode10.3
        env: CONAN_APPLE_CLANG_VERSIONS=10.0
      - <<: *osx
        osx_image: xcode11.3
        env: CONAN_APPLE_CLANG_VERSIONS=11.0

install:
  - chmod +x .ci/install.sh
  - ./.ci/install.sh

script:
  - chmod +x .ci/run.sh
  - ./.ci/run.sh
